name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      REGISTRY:   ghcr.io
      IMAGE_NAME: oss4u/terragrunt-github-actions
      IMAGE_TAGS: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2.2.1
        with:
          image:       ${{ env.IMAGE_NAME }}
          tags:        ${{ env.IMAGE_TAGS }}
          dockerfiles: ./Dockerfile
    
      - name: Push To GitHub Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image:       ${{ steps.build-image.outputs.image }}
          tags:        ${{ steps.build-image.outputs.tags }}
          registry:    ${{ env.REGISTRY }}
          username:    ${{ secrets.GHCR_USER }}
          password:    ${{ secrets.GHCR_TOKEN }}
