name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2.2.1
        with:
          image:       ghcr.io/oss4u/terragrunt-github-actions
          tags:        latest 
          dockerfiles: ./Dockerfile
    
      - name: Push To GitHub Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image:       ghcr.io/oss4u/terragrunt-github-actions
          tags:        latest 
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
